/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_windowaffiche (void);
GtkWidget* create_windowajout (void);
GtkWidget* create_dialogconfirmer (void);
GtkWidget* create_windowmodifier_ (void);
GtkWidget* create_dialogconfirmermodif (void);
GtkWidget* create_windowchercher01 (void);
GtkWidget* create_windowresultatrecherche (void);
GtkWidget* create_dialogconfsuppr (void);
