/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_AfficherObservateur (void);
GtkWidget* create_AjouterObservateur (void);
GtkWidget* create_ModifierObservateur (void);
GtkWidget* create_SupprimerObservateur (void);
