/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_AfficherObservateur (void)
{
  GtkWidget *AfficherObservateur;
  GtkWidget *fixed1;
  GtkWidget *treeview_ob;
  GtkWidget *entry_chercherob;
  GtkWidget *label1;
  GtkWidget *label_chercherob;
  GtkWidget *button_page_ajouter;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label3;
  GtkWidget *button_modifier_page;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label2;
  GtkWidget *button_supp_page;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label4;
  GtkWidget *chercherob;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image5;
  GtkWidget *label7;
  GtkWidget *button_affiche_dec;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image4;
  GtkWidget *label6;

  AfficherObservateur = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (AfficherObservateur), _("AfficherObservateur"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (AfficherObservateur), fixed1);

  treeview_ob = gtk_tree_view_new ();
  gtk_widget_show (treeview_ob);
  gtk_fixed_put (GTK_FIXED (fixed1), treeview_ob, 200, 112);
  gtk_widget_set_size_request (treeview_ob, 300, 200);

  entry_chercherob = gtk_entry_new ();
  gtk_widget_show (entry_chercherob);
  gtk_fixed_put (GTK_FIXED (fixed1), entry_chercherob, 272, 72);
  gtk_widget_set_size_request (entry_chercherob, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_chercherob), 8226);

  label1 = gtk_label_new (_("Liste des observateurs"));
  gtk_widget_show (label1);
  gtk_fixed_put (GTK_FIXED (fixed1), label1, 264, 16);
  gtk_widget_set_size_request (label1, 248, 48);

  label_chercherob = gtk_label_new (_("Chercher par id"));
  gtk_widget_show (label_chercherob);
  gtk_fixed_put (GTK_FIXED (fixed1), label_chercherob, 152, 80);
  gtk_widget_set_size_request (label_chercherob, 104, 17);

  button_page_ajouter = gtk_button_new ();
  gtk_widget_show (button_page_ajouter);
  gtk_fixed_put (GTK_FIXED (fixed1), button_page_ajouter, 368, 336);
  gtk_widget_set_size_request (button_page_ajouter, 88, 32);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (button_page_ajouter), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label3 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label3);
  gtk_box_pack_start (GTK_BOX (hbox2), label3, FALSE, FALSE, 0);

  button_modifier_page = gtk_button_new ();
  gtk_widget_show (button_modifier_page);
  gtk_fixed_put (GTK_FIXED (fixed1), button_modifier_page, 240, 336);
  gtk_widget_set_size_request (button_modifier_page, 88, 29);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (button_modifier_page), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label2 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label2);
  gtk_box_pack_start (GTK_BOX (hbox1), label2, FALSE, FALSE, 0);

  button_supp_page = gtk_button_new ();
  gtk_widget_show (button_supp_page);
  gtk_fixed_put (GTK_FIXED (fixed1), button_supp_page, 312, 376);
  gtk_widget_set_size_request (button_supp_page, 112, 32);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (button_supp_page), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label4 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label4);
  gtk_box_pack_start (GTK_BOX (hbox3), label4, FALSE, FALSE, 0);

  chercherob = gtk_button_new ();
  gtk_widget_show (chercherob);
  gtk_fixed_put (GTK_FIXED (fixed1), chercherob, 456, 72);
  gtk_widget_set_size_request (chercherob, 120, 29);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (chercherob), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image5 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox5), image5, FALSE, FALSE, 0);

  label7 = gtk_label_new_with_mnemonic (_("Chercher"));
  gtk_widget_show (label7);
  gtk_box_pack_start (GTK_BOX (hbox5), label7, FALSE, FALSE, 0);

  button_affiche_dec = gtk_button_new ();
  gtk_widget_show (button_affiche_dec);
  gtk_fixed_put (GTK_FIXED (fixed1), button_affiche_dec, 688, 0);
  gtk_widget_set_size_request (button_affiche_dec, 128, 32);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (button_affiche_dec), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image4 = gtk_image_new_from_stock ("gtk-quit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox4), image4, FALSE, FALSE, 0);

  label6 = gtk_label_new_with_mnemonic (_("D\303\251connexion"));
  gtk_widget_show (label6);
  gtk_box_pack_start (GTK_BOX (hbox4), label6, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) treeview_ob, "row_activated",
                    G_CALLBACK (on_treeview_ob_row_activated),
                    NULL);
  g_signal_connect ((gpointer) button_page_ajouter, "clicked",
                    G_CALLBACK (on_button_page_ajouter_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_modifier_page, "clicked",
                    G_CALLBACK (on_button_modifier_page_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_supp_page, "clicked",
                    G_CALLBACK (on_button_supp_page_clicked),
                    NULL);
  g_signal_connect ((gpointer) chercherob, "clicked",
                    G_CALLBACK (on_chercherob_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_affiche_dec, "clicked",
                    G_CALLBACK (on_button_affiche_dec_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (AfficherObservateur, AfficherObservateur, "AfficherObservateur");
  GLADE_HOOKUP_OBJECT (AfficherObservateur, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (AfficherObservateur, treeview_ob, "treeview_ob");
  GLADE_HOOKUP_OBJECT (AfficherObservateur, entry_chercherob, "entry_chercherob");
  GLADE_HOOKUP_OBJECT (AfficherObservateur, label1, "label1");
  GLADE_HOOKUP_OBJECT (AfficherObservateur, label_chercherob, "label_chercherob");
  GLADE_HOOKUP_OBJECT (AfficherObservateur, button_page_ajouter, "button_page_ajouter");
  GLADE_HOOKUP_OBJECT (AfficherObservateur, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (AfficherObservateur, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (AfficherObservateur, image2, "image2");
  GLADE_HOOKUP_OBJECT (AfficherObservateur, label3, "label3");
  GLADE_HOOKUP_OBJECT (AfficherObservateur, button_modifier_page, "button_modifier_page");
  GLADE_HOOKUP_OBJECT (AfficherObservateur, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (AfficherObservateur, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (AfficherObservateur, image1, "image1");
  GLADE_HOOKUP_OBJECT (AfficherObservateur, label2, "label2");
  GLADE_HOOKUP_OBJECT (AfficherObservateur, button_supp_page, "button_supp_page");
  GLADE_HOOKUP_OBJECT (AfficherObservateur, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (AfficherObservateur, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (AfficherObservateur, image3, "image3");
  GLADE_HOOKUP_OBJECT (AfficherObservateur, label4, "label4");
  GLADE_HOOKUP_OBJECT (AfficherObservateur, chercherob, "chercherob");
  GLADE_HOOKUP_OBJECT (AfficherObservateur, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (AfficherObservateur, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (AfficherObservateur, image5, "image5");
  GLADE_HOOKUP_OBJECT (AfficherObservateur, label7, "label7");
  GLADE_HOOKUP_OBJECT (AfficherObservateur, button_affiche_dec, "button_affiche_dec");
  GLADE_HOOKUP_OBJECT (AfficherObservateur, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (AfficherObservateur, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (AfficherObservateur, image4, "image4");
  GLADE_HOOKUP_OBJECT (AfficherObservateur, label6, "label6");

  return AfficherObservateur;
}

GtkWidget*
create_AjouterObservateur (void)
{
  GtkWidget *AjouterObservateur;
  GtkWidget *fixed2;
  GtkWidget *entry_id_ob;
  GtkWidget *entry_nom_ob;
  GtkWidget *entry_prenom_ob;
  GtkObject *spinbutton_jour_adj;
  GtkWidget *spinbutton_jour;
  GtkObject *spinbutton_mois_adj;
  GtkWidget *spinbutton_mois;
  GtkObject *spinbutton_annee_adj;
  GtkWidget *spinbutton_annee;
  GtkWidget *label8;
  GtkWidget *label10;
  GtkWidget *label11;
  GtkWidget *label12;
  GtkWidget *label13;
  GtkWidget *label14;
  GtkWidget *label15;
  GtkWidget *label16;
  GtkWidget *label18;
  GtkWidget *combobox_profession;
  GtkWidget *button_ajouter_dec;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image7;
  GtkWidget *label17;
  GtkWidget *button_afficher_treeview_ajout;
  GtkWidget *alignment9;
  GtkWidget *hbox9;
  GtkWidget *image9;
  GtkWidget *label20;
  GtkWidget *button_valider_ob_ajouter;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *image8;
  GtkWidget *label19;
  GtkWidget *button_prece_ajouter;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image6;
  GtkWidget *label9;
  GtkWidget *radiobutton_homme_ob;
  GSList *radiobutton_homme_ob_group = NULL;
  GtkWidget *checkbutton_nonetranger;
  GtkWidget *radiobutton_femme_ob;
  GtkWidget *checkbutton_etranger;

  AjouterObservateur = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (AjouterObservateur), _("AjouterObservateur"));

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (AjouterObservateur), fixed2);

  entry_id_ob = gtk_entry_new ();
  gtk_widget_show (entry_id_ob);
  gtk_fixed_put (GTK_FIXED (fixed2), entry_id_ob, 288, 144);
  gtk_widget_set_size_request (entry_id_ob, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_id_ob), 8226);

  entry_nom_ob = gtk_entry_new ();
  gtk_widget_show (entry_nom_ob);
  gtk_fixed_put (GTK_FIXED (fixed2), entry_nom_ob, 288, 200);
  gtk_widget_set_size_request (entry_nom_ob, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_nom_ob), 8226);

  entry_prenom_ob = gtk_entry_new ();
  gtk_widget_show (entry_prenom_ob);
  gtk_fixed_put (GTK_FIXED (fixed2), entry_prenom_ob, 288, 256);
  gtk_widget_set_size_request (entry_prenom_ob, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_prenom_ob), 8226);

  spinbutton_jour_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbutton_jour = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_jour_adj), 1, 0);
  gtk_widget_show (spinbutton_jour);
  gtk_fixed_put (GTK_FIXED (fixed2), spinbutton_jour, 296, 320);
  gtk_widget_set_size_request (spinbutton_jour, 60, 27);

  spinbutton_mois_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbutton_mois = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_mois_adj), 1, 0);
  gtk_widget_show (spinbutton_mois);
  gtk_fixed_put (GTK_FIXED (fixed2), spinbutton_mois, 392, 320);
  gtk_widget_set_size_request (spinbutton_mois, 60, 27);

  spinbutton_annee_adj = gtk_adjustment_new (1990, 1800, 3000, 1, 10, 10);
  spinbutton_annee = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_annee_adj), 1, 0);
  gtk_widget_show (spinbutton_annee);
  gtk_fixed_put (GTK_FIXED (fixed2), spinbutton_annee, 504, 320);
  gtk_widget_set_size_request (spinbutton_annee, 60, 27);

  label8 = gtk_label_new ("");
  gtk_widget_show (label8);
  gtk_fixed_put (GTK_FIXED (fixed2), label8, 488, 552);
  gtk_widget_set_size_request (label8, 49, 17);

  label10 = gtk_label_new (_("Identifiant :"));
  gtk_widget_show (label10);
  gtk_fixed_put (GTK_FIXED (fixed2), label10, 136, 144);
  gtk_widget_set_size_request (label10, 105, 16);

  label11 = gtk_label_new (_("Pr\303\251nom :"));
  gtk_widget_show (label11);
  gtk_fixed_put (GTK_FIXED (fixed2), label11, 144, 264);
  gtk_widget_set_size_request (label11, 81, 17);

  label12 = gtk_label_new (_("Nom :"));
  gtk_widget_show (label12);
  gtk_fixed_put (GTK_FIXED (fixed2), label12, 152, 216);
  gtk_widget_set_size_request (label12, 49, 17);

  label13 = gtk_label_new (_("Age :"));
  gtk_widget_show (label13);
  gtk_fixed_put (GTK_FIXED (fixed2), label13, 152, 320);
  gtk_widget_set_size_request (label13, 49, 17);

  label14 = gtk_label_new (_("Profession :"));
  gtk_widget_show (label14);
  gtk_fixed_put (GTK_FIXED (fixed2), label14, 152, 384);
  gtk_widget_set_size_request (label14, 80, 25);

  label15 = gtk_label_new (_("Genre :"));
  gtk_widget_show (label15);
  gtk_fixed_put (GTK_FIXED (fixed2), label15, 160, 432);
  gtk_widget_set_size_request (label15, 49, 16);

  label16 = gtk_label_new (_("Nationalit\303\251 :"));
  gtk_widget_show (label16);
  gtk_fixed_put (GTK_FIXED (fixed2), label16, 136, 472);
  gtk_widget_set_size_request (label16, 113, 41);

  label18 = gtk_label_new (_("Ajouter un nouveau observateur"));
  gtk_widget_show (label18);
  gtk_fixed_put (GTK_FIXED (fixed2), label18, 184, 48);
  gtk_widget_set_size_request (label18, 265, 25);

  combobox_profession = gtk_combo_box_new_text ();
  gtk_widget_show (combobox_profession);
  gtk_fixed_put (GTK_FIXED (fixed2), combobox_profession, 288, 368);
  gtk_widget_set_size_request (combobox_profession, 168, 39);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_profession), _("Administration"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_profession), _("Sant\303\251"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_profession), _("Justice et protection du public"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_profession), _("Technologies de l'information"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_profession), _("Arts"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_profession), _("Ressources naturelles et agriculture"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_profession), _("Enseignement"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_profession), _("Tourisme et h\303\264tellerie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_profession), _("Comptabilit\303\251 et finance"));

  button_ajouter_dec = gtk_button_new ();
  gtk_widget_show (button_ajouter_dec);
  gtk_fixed_put (GTK_FIXED (fixed2), button_ajouter_dec, 688, 0);
  gtk_widget_set_size_request (button_ajouter_dec, 128, 32);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (button_ajouter_dec), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image7 = gtk_image_new_from_stock ("gtk-quit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox7), image7, FALSE, FALSE, 0);

  label17 = gtk_label_new_with_mnemonic (_("D\303\251connexion"));
  gtk_widget_show (label17);
  gtk_box_pack_start (GTK_BOX (hbox7), label17, FALSE, FALSE, 0);

  button_afficher_treeview_ajout = gtk_button_new ();
  gtk_widget_show (button_afficher_treeview_ajout);
  gtk_fixed_put (GTK_FIXED (fixed2), button_afficher_treeview_ajout, 560, 528);
  gtk_widget_set_size_request (button_afficher_treeview_ajout, 96, 40);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (button_afficher_treeview_ajout), alignment9);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox9);

  image9 = gtk_image_new_from_stock ("gtk-media-play", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox9), image9, FALSE, FALSE, 0);

  label20 = gtk_label_new_with_mnemonic (_("afficher"));
  gtk_widget_show (label20);
  gtk_box_pack_start (GTK_BOX (hbox9), label20, FALSE, FALSE, 0);

  button_valider_ob_ajouter = gtk_button_new ();
  gtk_widget_show (button_valider_ob_ajouter);
  gtk_fixed_put (GTK_FIXED (fixed2), button_valider_ob_ajouter, 376, 528);
  gtk_widget_set_size_request (button_valider_ob_ajouter, 104, 37);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (button_valider_ob_ajouter), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  image8 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox8), image8, FALSE, FALSE, 0);

  label19 = gtk_label_new_with_mnemonic (_("valider"));
  gtk_widget_show (label19);
  gtk_box_pack_start (GTK_BOX (hbox8), label19, FALSE, FALSE, 0);

  button_prece_ajouter = gtk_button_new ();
  gtk_widget_show (button_prece_ajouter);
  gtk_fixed_put (GTK_FIXED (fixed2), button_prece_ajouter, 8, 552);
  gtk_widget_set_size_request (button_prece_ajouter, 152, 29);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (button_prece_ajouter), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image6 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox6), image6, FALSE, FALSE, 0);

  label9 = gtk_label_new_with_mnemonic (_("Page pr\303\251c\303\250dente"));
  gtk_widget_show (label9);
  gtk_box_pack_start (GTK_BOX (hbox6), label9, FALSE, FALSE, 0);

  radiobutton_homme_ob = gtk_radio_button_new_with_mnemonic (NULL, _("homme"));
  gtk_widget_show (radiobutton_homme_ob);
  gtk_fixed_put (GTK_FIXED (fixed2), radiobutton_homme_ob, 328, 432);
  gtk_widget_set_size_request (radiobutton_homme_ob, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton_homme_ob), radiobutton_homme_ob_group);
  radiobutton_homme_ob_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton_homme_ob));

  checkbutton_nonetranger = gtk_check_button_new_with_mnemonic (_("non etranger"));
  gtk_widget_show (checkbutton_nonetranger);
  gtk_fixed_put (GTK_FIXED (fixed2), checkbutton_nonetranger, 280, 480);
  gtk_widget_set_size_request (checkbutton_nonetranger, 118, 24);

  radiobutton_femme_ob = gtk_radio_button_new_with_mnemonic (NULL, _("femme"));
  gtk_widget_show (radiobutton_femme_ob);
  gtk_fixed_put (GTK_FIXED (fixed2), radiobutton_femme_ob, 512, 432);
  gtk_widget_set_size_request (radiobutton_femme_ob, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton_femme_ob), radiobutton_homme_ob_group);
  radiobutton_homme_ob_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton_femme_ob));

  checkbutton_etranger = gtk_check_button_new_with_mnemonic (_("etranger"));
  gtk_widget_show (checkbutton_etranger);
  gtk_fixed_put (GTK_FIXED (fixed2), checkbutton_etranger, 456, 480);
  gtk_widget_set_size_request (checkbutton_etranger, 118, 24);

  g_signal_connect ((gpointer) button_ajouter_dec, "clicked",
                    G_CALLBACK (on_button_ajouter_dec_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_afficher_treeview_ajout, "clicked",
                    G_CALLBACK (on_button_afficher_treeview_ajout_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_valider_ob_ajouter, "clicked",
                    G_CALLBACK (on_button_valider_ob_ajouter_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_prece_ajouter, "clicked",
                    G_CALLBACK (on_button_prece_ajouter_clicked),
                    NULL);
  g_signal_connect ((gpointer) radiobutton_homme_ob, "toggled",
                    G_CALLBACK (on_radiobutton_homme_ob_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton_nonetranger, "toggled",
                    G_CALLBACK (on_checkbutton_nonetranger_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton_femme_ob, "toggled",
                    G_CALLBACK (on_radiobutton_femme_ob_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton_etranger, "toggled",
                    G_CALLBACK (on_checkbutton_etranger_toggled),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (AjouterObservateur, AjouterObservateur, "AjouterObservateur");
  GLADE_HOOKUP_OBJECT (AjouterObservateur, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (AjouterObservateur, entry_id_ob, "entry_id_ob");
  GLADE_HOOKUP_OBJECT (AjouterObservateur, entry_nom_ob, "entry_nom_ob");
  GLADE_HOOKUP_OBJECT (AjouterObservateur, entry_prenom_ob, "entry_prenom_ob");
  GLADE_HOOKUP_OBJECT (AjouterObservateur, spinbutton_jour, "spinbutton_jour");
  GLADE_HOOKUP_OBJECT (AjouterObservateur, spinbutton_mois, "spinbutton_mois");
  GLADE_HOOKUP_OBJECT (AjouterObservateur, spinbutton_annee, "spinbutton_annee");
  GLADE_HOOKUP_OBJECT (AjouterObservateur, label8, "label8");
  GLADE_HOOKUP_OBJECT (AjouterObservateur, label10, "label10");
  GLADE_HOOKUP_OBJECT (AjouterObservateur, label11, "label11");
  GLADE_HOOKUP_OBJECT (AjouterObservateur, label12, "label12");
  GLADE_HOOKUP_OBJECT (AjouterObservateur, label13, "label13");
  GLADE_HOOKUP_OBJECT (AjouterObservateur, label14, "label14");
  GLADE_HOOKUP_OBJECT (AjouterObservateur, label15, "label15");
  GLADE_HOOKUP_OBJECT (AjouterObservateur, label16, "label16");
  GLADE_HOOKUP_OBJECT (AjouterObservateur, label18, "label18");
  GLADE_HOOKUP_OBJECT (AjouterObservateur, combobox_profession, "combobox_profession");
  GLADE_HOOKUP_OBJECT (AjouterObservateur, button_ajouter_dec, "button_ajouter_dec");
  GLADE_HOOKUP_OBJECT (AjouterObservateur, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (AjouterObservateur, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (AjouterObservateur, image7, "image7");
  GLADE_HOOKUP_OBJECT (AjouterObservateur, label17, "label17");
  GLADE_HOOKUP_OBJECT (AjouterObservateur, button_afficher_treeview_ajout, "button_afficher_treeview_ajout");
  GLADE_HOOKUP_OBJECT (AjouterObservateur, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (AjouterObservateur, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (AjouterObservateur, image9, "image9");
  GLADE_HOOKUP_OBJECT (AjouterObservateur, label20, "label20");
  GLADE_HOOKUP_OBJECT (AjouterObservateur, button_valider_ob_ajouter, "button_valider_ob_ajouter");
  GLADE_HOOKUP_OBJECT (AjouterObservateur, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (AjouterObservateur, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (AjouterObservateur, image8, "image8");
  GLADE_HOOKUP_OBJECT (AjouterObservateur, label19, "label19");
  GLADE_HOOKUP_OBJECT (AjouterObservateur, button_prece_ajouter, "button_prece_ajouter");
  GLADE_HOOKUP_OBJECT (AjouterObservateur, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (AjouterObservateur, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (AjouterObservateur, image6, "image6");
  GLADE_HOOKUP_OBJECT (AjouterObservateur, label9, "label9");
  GLADE_HOOKUP_OBJECT (AjouterObservateur, radiobutton_homme_ob, "radiobutton_homme_ob");
  GLADE_HOOKUP_OBJECT (AjouterObservateur, checkbutton_nonetranger, "checkbutton_nonetranger");
  GLADE_HOOKUP_OBJECT (AjouterObservateur, radiobutton_femme_ob, "radiobutton_femme_ob");
  GLADE_HOOKUP_OBJECT (AjouterObservateur, checkbutton_etranger, "checkbutton_etranger");

  return AjouterObservateur;
}

GtkWidget*
create_ModifierObservateur (void)
{
  GtkWidget *ModifierObservateur;
  GtkWidget *fixed3;
  GtkWidget *entry_cherch_mod_id;
  GtkWidget *entry_mod_nom;
  GtkWidget *entry_mod_prenom;
  GtkObject *spinbutton_mod_j_adj;
  GtkWidget *spinbutton_mod_j;
  GtkObject *spinbutton_mod_m_adj;
  GtkWidget *spinbutton_mod_m;
  GtkObject *spinbutton_mod_a_adj;
  GtkWidget *spinbutton_mod_a;
  GtkWidget *label21;
  GtkWidget *label22;
  GtkWidget *label23;
  GtkWidget *label24;
  GtkWidget *label25;
  GtkWidget *label26;
  GtkWidget *label27;
  GtkWidget *label29;
  GtkWidget *label30;
  GtkWidget *combobox_profession;
  GtkWidget *butto_cherch_id_mod;
  GtkWidget *image11;
  GtkWidget *button_valider_modifier;
  GtkWidget *alignment10;
  GtkWidget *hbox10;
  GtkWidget *image10;
  GtkWidget *label28;
  GtkWidget *button_afficher_mod;
  GtkWidget *alignment13;
  GtkWidget *hbox13;
  GtkWidget *image14;
  GtkWidget *label33;
  GtkWidget *button_prece_modifier;
  GtkWidget *alignment11;
  GtkWidget *hbox11;
  GtkWidget *image12;
  GtkWidget *label31;
  GtkWidget *button_modifier_dec;
  GtkWidget *alignment12;
  GtkWidget *hbox12;
  GtkWidget *image13;
  GtkWidget *label32;
  GtkWidget *radiobutton_homme_ob;
  GSList *radiobutton_homme_ob_group = NULL;
  GtkWidget *radiobutton_femme_ob;
  GtkWidget *checkbutton_etranger;
  GtkWidget *checkbutton_nonetranger;

  ModifierObservateur = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (ModifierObservateur), _("ModifierObservateur"));

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (ModifierObservateur), fixed3);

  entry_cherch_mod_id = gtk_entry_new ();
  gtk_widget_show (entry_cherch_mod_id);
  gtk_fixed_put (GTK_FIXED (fixed3), entry_cherch_mod_id, 264, 104);
  gtk_widget_set_size_request (entry_cherch_mod_id, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_cherch_mod_id), 8226);

  entry_mod_nom = gtk_entry_new ();
  gtk_widget_show (entry_mod_nom);
  gtk_fixed_put (GTK_FIXED (fixed3), entry_mod_nom, 288, 200);
  gtk_widget_set_size_request (entry_mod_nom, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_mod_nom), 8226);

  entry_mod_prenom = gtk_entry_new ();
  gtk_widget_show (entry_mod_prenom);
  gtk_fixed_put (GTK_FIXED (fixed3), entry_mod_prenom, 288, 256);
  gtk_widget_set_size_request (entry_mod_prenom, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_mod_prenom), 8226);

  spinbutton_mod_j_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbutton_mod_j = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_mod_j_adj), 1, 0);
  gtk_widget_show (spinbutton_mod_j);
  gtk_fixed_put (GTK_FIXED (fixed3), spinbutton_mod_j, 296, 320);
  gtk_widget_set_size_request (spinbutton_mod_j, 60, 27);

  spinbutton_mod_m_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbutton_mod_m = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_mod_m_adj), 1, 0);
  gtk_widget_show (spinbutton_mod_m);
  gtk_fixed_put (GTK_FIXED (fixed3), spinbutton_mod_m, 392, 320);
  gtk_widget_set_size_request (spinbutton_mod_m, 60, 27);

  spinbutton_mod_a_adj = gtk_adjustment_new (1990, 1800, 3000, 1, 10, 10);
  spinbutton_mod_a = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_mod_a_adj), 1, 0);
  gtk_widget_show (spinbutton_mod_a);
  gtk_fixed_put (GTK_FIXED (fixed3), spinbutton_mod_a, 504, 320);
  gtk_widget_set_size_request (spinbutton_mod_a, 60, 27);

  label21 = gtk_label_new ("");
  gtk_widget_show (label21);
  gtk_fixed_put (GTK_FIXED (fixed3), label21, 488, 552);
  gtk_widget_set_size_request (label21, 49, 17);

  label22 = gtk_label_new (_("Pr\303\251nom :"));
  gtk_widget_show (label22);
  gtk_fixed_put (GTK_FIXED (fixed3), label22, 144, 264);
  gtk_widget_set_size_request (label22, 81, 17);

  label23 = gtk_label_new (_("Nom :"));
  gtk_widget_show (label23);
  gtk_fixed_put (GTK_FIXED (fixed3), label23, 152, 216);
  gtk_widget_set_size_request (label23, 49, 17);

  label24 = gtk_label_new (_("Age :"));
  gtk_widget_show (label24);
  gtk_fixed_put (GTK_FIXED (fixed3), label24, 152, 320);
  gtk_widget_set_size_request (label24, 49, 17);

  label25 = gtk_label_new (_("Profession :"));
  gtk_widget_show (label25);
  gtk_fixed_put (GTK_FIXED (fixed3), label25, 152, 384);
  gtk_widget_set_size_request (label25, 80, 25);

  label26 = gtk_label_new (_("Genre :"));
  gtk_widget_show (label26);
  gtk_fixed_put (GTK_FIXED (fixed3), label26, 160, 432);
  gtk_widget_set_size_request (label26, 49, 16);

  label27 = gtk_label_new (_("Nationalit\303\251 :"));
  gtk_widget_show (label27);
  gtk_fixed_put (GTK_FIXED (fixed3), label27, 136, 472);
  gtk_widget_set_size_request (label27, 113, 41);

  label29 = gtk_label_new (_("Donner un Identifiant :"));
  gtk_widget_show (label29);
  gtk_fixed_put (GTK_FIXED (fixed3), label29, 80, 104);
  gtk_widget_set_size_request (label29, 160, 32);

  label30 = gtk_label_new (_("Modifier un  observateur"));
  gtk_widget_show (label30);
  gtk_fixed_put (GTK_FIXED (fixed3), label30, 192, 24);
  gtk_widget_set_size_request (label30, 265, 25);

  combobox_profession = gtk_combo_box_new_text ();
  gtk_widget_show (combobox_profession);
  gtk_fixed_put (GTK_FIXED (fixed3), combobox_profession, 288, 368);
  gtk_widget_set_size_request (combobox_profession, 168, 39);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_profession), _("Administration"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_profession), _("Sant\303\251"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_profession), _("Justice et protection du public"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_profession), _("Technologies de l'information"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_profession), _("Arts"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_profession), _("Ressources naturelles et agriculture"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_profession), _("Enseignement"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_profession), _("Tourisme et h\303\264tellerie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_profession), _("Comptabilit\303\251 et finance"));

  butto_cherch_id_mod = gtk_button_new ();
  gtk_widget_show (butto_cherch_id_mod);
  gtk_fixed_put (GTK_FIXED (fixed3), butto_cherch_id_mod, 440, 104);
  gtk_widget_set_size_request (butto_cherch_id_mod, 74, 29);

  image11 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image11);
  gtk_container_add (GTK_CONTAINER (butto_cherch_id_mod), image11);

  button_valider_modifier = gtk_button_new ();
  gtk_widget_show (button_valider_modifier);
  gtk_fixed_put (GTK_FIXED (fixed3), button_valider_modifier, 376, 528);
  gtk_widget_set_size_request (button_valider_modifier, 104, 37);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (button_valider_modifier), alignment10);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox10);

  image10 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image10);
  gtk_box_pack_start (GTK_BOX (hbox10), image10, FALSE, FALSE, 0);

  label28 = gtk_label_new_with_mnemonic (_("valider"));
  gtk_widget_show (label28);
  gtk_box_pack_start (GTK_BOX (hbox10), label28, FALSE, FALSE, 0);

  button_afficher_mod = gtk_button_new ();
  gtk_widget_show (button_afficher_mod);
  gtk_fixed_put (GTK_FIXED (fixed3), button_afficher_mod, 560, 528);
  gtk_widget_set_size_request (button_afficher_mod, 96, 40);

  alignment13 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment13);
  gtk_container_add (GTK_CONTAINER (button_afficher_mod), alignment13);

  hbox13 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox13);
  gtk_container_add (GTK_CONTAINER (alignment13), hbox13);

  image14 = gtk_image_new_from_stock ("gtk-media-play", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image14);
  gtk_box_pack_start (GTK_BOX (hbox13), image14, FALSE, FALSE, 0);

  label33 = gtk_label_new_with_mnemonic (_("afficher"));
  gtk_widget_show (label33);
  gtk_box_pack_start (GTK_BOX (hbox13), label33, FALSE, FALSE, 0);

  button_prece_modifier = gtk_button_new ();
  gtk_widget_show (button_prece_modifier);
  gtk_fixed_put (GTK_FIXED (fixed3), button_prece_modifier, 8, 552);
  gtk_widget_set_size_request (button_prece_modifier, 152, 29);

  alignment11 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment11);
  gtk_container_add (GTK_CONTAINER (button_prece_modifier), alignment11);

  hbox11 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox11);
  gtk_container_add (GTK_CONTAINER (alignment11), hbox11);

  image12 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image12);
  gtk_box_pack_start (GTK_BOX (hbox11), image12, FALSE, FALSE, 0);

  label31 = gtk_label_new_with_mnemonic (_("Page pr\303\251c\303\250dente"));
  gtk_widget_show (label31);
  gtk_box_pack_start (GTK_BOX (hbox11), label31, FALSE, FALSE, 0);

  button_modifier_dec = gtk_button_new ();
  gtk_widget_show (button_modifier_dec);
  gtk_fixed_put (GTK_FIXED (fixed3), button_modifier_dec, 688, 0);
  gtk_widget_set_size_request (button_modifier_dec, 128, 32);

  alignment12 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment12);
  gtk_container_add (GTK_CONTAINER (button_modifier_dec), alignment12);

  hbox12 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox12);
  gtk_container_add (GTK_CONTAINER (alignment12), hbox12);

  image13 = gtk_image_new_from_stock ("gtk-quit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image13);
  gtk_box_pack_start (GTK_BOX (hbox12), image13, FALSE, FALSE, 0);

  label32 = gtk_label_new_with_mnemonic (_("D\303\251connexion"));
  gtk_widget_show (label32);
  gtk_box_pack_start (GTK_BOX (hbox12), label32, FALSE, FALSE, 0);

  radiobutton_homme_ob = gtk_radio_button_new_with_mnemonic (NULL, _("homme"));
  gtk_widget_show (radiobutton_homme_ob);
  gtk_fixed_put (GTK_FIXED (fixed3), radiobutton_homme_ob, 328, 432);
  gtk_widget_set_size_request (radiobutton_homme_ob, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton_homme_ob), radiobutton_homme_ob_group);
  radiobutton_homme_ob_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton_homme_ob));

  radiobutton_femme_ob = gtk_radio_button_new_with_mnemonic (NULL, _("femme"));
  gtk_widget_show (radiobutton_femme_ob);
  gtk_fixed_put (GTK_FIXED (fixed3), radiobutton_femme_ob, 568, 440);
  gtk_widget_set_size_request (radiobutton_femme_ob, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton_femme_ob), radiobutton_homme_ob_group);
  radiobutton_homme_ob_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton_femme_ob));

  checkbutton_etranger = gtk_check_button_new_with_mnemonic (_("etranger"));
  gtk_widget_show (checkbutton_etranger);
  gtk_fixed_put (GTK_FIXED (fixed3), checkbutton_etranger, 576, 480);
  gtk_widget_set_size_request (checkbutton_etranger, 118, 24);

  checkbutton_nonetranger = gtk_check_button_new_with_mnemonic (_("non etranger"));
  gtk_widget_show (checkbutton_nonetranger);
  gtk_fixed_put (GTK_FIXED (fixed3), checkbutton_nonetranger, 352, 480);
  gtk_widget_set_size_request (checkbutton_nonetranger, 118, 24);

  g_signal_connect ((gpointer) butto_cherch_id_mod, "clicked",
                    G_CALLBACK (on_butto_cherch_id_mod_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_valider_modifier, "clicked",
                    G_CALLBACK (on_button_valider_modifier_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_afficher_mod, "clicked",
                    G_CALLBACK (on_button_afficher_mod_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_prece_modifier, "clicked",
                    G_CALLBACK (on_button_prece_modifier_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_modifier_dec, "clicked",
                    G_CALLBACK (on_button_modifier_dec_clicked),
                    NULL);
  g_signal_connect ((gpointer) radiobutton_homme_ob, "toggled",
                    G_CALLBACK (on_radiobutton_homme_ob_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton_femme_ob, "toggled",
                    G_CALLBACK (on_radiobutton_femme_ob_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton_etranger, "toggled",
                    G_CALLBACK (on_checkbutton_etranger_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton_nonetranger, "toggled",
                    G_CALLBACK (on_checkbutton_nonetranger_toggled),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (ModifierObservateur, ModifierObservateur, "ModifierObservateur");
  GLADE_HOOKUP_OBJECT (ModifierObservateur, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (ModifierObservateur, entry_cherch_mod_id, "entry_cherch_mod_id");
  GLADE_HOOKUP_OBJECT (ModifierObservateur, entry_mod_nom, "entry_mod_nom");
  GLADE_HOOKUP_OBJECT (ModifierObservateur, entry_mod_prenom, "entry_mod_prenom");
  GLADE_HOOKUP_OBJECT (ModifierObservateur, spinbutton_mod_j, "spinbutton_mod_j");
  GLADE_HOOKUP_OBJECT (ModifierObservateur, spinbutton_mod_m, "spinbutton_mod_m");
  GLADE_HOOKUP_OBJECT (ModifierObservateur, spinbutton_mod_a, "spinbutton_mod_a");
  GLADE_HOOKUP_OBJECT (ModifierObservateur, label21, "label21");
  GLADE_HOOKUP_OBJECT (ModifierObservateur, label22, "label22");
  GLADE_HOOKUP_OBJECT (ModifierObservateur, label23, "label23");
  GLADE_HOOKUP_OBJECT (ModifierObservateur, label24, "label24");
  GLADE_HOOKUP_OBJECT (ModifierObservateur, label25, "label25");
  GLADE_HOOKUP_OBJECT (ModifierObservateur, label26, "label26");
  GLADE_HOOKUP_OBJECT (ModifierObservateur, label27, "label27");
  GLADE_HOOKUP_OBJECT (ModifierObservateur, label29, "label29");
  GLADE_HOOKUP_OBJECT (ModifierObservateur, label30, "label30");
  GLADE_HOOKUP_OBJECT (ModifierObservateur, combobox_profession, "combobox_profession");
  GLADE_HOOKUP_OBJECT (ModifierObservateur, butto_cherch_id_mod, "butto_cherch_id_mod");
  GLADE_HOOKUP_OBJECT (ModifierObservateur, image11, "image11");
  GLADE_HOOKUP_OBJECT (ModifierObservateur, button_valider_modifier, "button_valider_modifier");
  GLADE_HOOKUP_OBJECT (ModifierObservateur, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (ModifierObservateur, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (ModifierObservateur, image10, "image10");
  GLADE_HOOKUP_OBJECT (ModifierObservateur, label28, "label28");
  GLADE_HOOKUP_OBJECT (ModifierObservateur, button_afficher_mod, "button_afficher_mod");
  GLADE_HOOKUP_OBJECT (ModifierObservateur, alignment13, "alignment13");
  GLADE_HOOKUP_OBJECT (ModifierObservateur, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (ModifierObservateur, image14, "image14");
  GLADE_HOOKUP_OBJECT (ModifierObservateur, label33, "label33");
  GLADE_HOOKUP_OBJECT (ModifierObservateur, button_prece_modifier, "button_prece_modifier");
  GLADE_HOOKUP_OBJECT (ModifierObservateur, alignment11, "alignment11");
  GLADE_HOOKUP_OBJECT (ModifierObservateur, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (ModifierObservateur, image12, "image12");
  GLADE_HOOKUP_OBJECT (ModifierObservateur, label31, "label31");
  GLADE_HOOKUP_OBJECT (ModifierObservateur, button_modifier_dec, "button_modifier_dec");
  GLADE_HOOKUP_OBJECT (ModifierObservateur, alignment12, "alignment12");
  GLADE_HOOKUP_OBJECT (ModifierObservateur, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (ModifierObservateur, image13, "image13");
  GLADE_HOOKUP_OBJECT (ModifierObservateur, label32, "label32");
  GLADE_HOOKUP_OBJECT (ModifierObservateur, radiobutton_homme_ob, "radiobutton_homme_ob");
  GLADE_HOOKUP_OBJECT (ModifierObservateur, radiobutton_femme_ob, "radiobutton_femme_ob");
  GLADE_HOOKUP_OBJECT (ModifierObservateur, checkbutton_etranger, "checkbutton_etranger");
  GLADE_HOOKUP_OBJECT (ModifierObservateur, checkbutton_nonetranger, "checkbutton_nonetranger");

  return ModifierObservateur;
}

GtkWidget*
create_SupprimerObservateur (void)
{
  GtkWidget *SupprimerObservateur;
  GtkWidget *fixed4;
  GtkWidget *entrycherchsupp;
  GtkWidget *label34;
  GtkWidget *label35;
  GtkWidget *button_supp_dec;
  GtkWidget *alignment15;
  GtkWidget *hbox15;
  GtkWidget *image17;
  GtkWidget *label37;
  GtkWidget *button_cherch_supp;
  GtkWidget *image15;
  GtkWidget *button_prece_supp;
  GtkWidget *alignment14;
  GtkWidget *hbox14;
  GtkWidget *image16;
  GtkWidget *label36;

  SupprimerObservateur = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (SupprimerObservateur), _("SupprimerObservateur"));

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (SupprimerObservateur), fixed4);

  entrycherchsupp = gtk_entry_new ();
  gtk_widget_show (entrycherchsupp);
  gtk_fixed_put (GTK_FIXED (fixed4), entrycherchsupp, 288, 120);
  gtk_widget_set_size_request (entrycherchsupp, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrycherchsupp), 8226);

  label34 = gtk_label_new (_("Donner l'identifiant :"));
  gtk_widget_show (label34);
  gtk_fixed_put (GTK_FIXED (fixed4), label34, 96, 104);
  gtk_widget_set_size_request (label34, 232, 56);

  label35 = gtk_label_new (_("Supprimer l identifiant"));
  gtk_widget_show (label35);
  gtk_fixed_put (GTK_FIXED (fixed4), label35, 288, 48);
  gtk_widget_set_size_request (label35, 201, 16);

  button_supp_dec = gtk_button_new ();
  gtk_widget_show (button_supp_dec);
  gtk_fixed_put (GTK_FIXED (fixed4), button_supp_dec, 688, 0);
  gtk_widget_set_size_request (button_supp_dec, 128, 32);

  alignment15 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment15);
  gtk_container_add (GTK_CONTAINER (button_supp_dec), alignment15);

  hbox15 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox15);
  gtk_container_add (GTK_CONTAINER (alignment15), hbox15);

  image17 = gtk_image_new_from_stock ("gtk-quit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image17);
  gtk_box_pack_start (GTK_BOX (hbox15), image17, FALSE, FALSE, 0);

  label37 = gtk_label_new_with_mnemonic (_("D\303\251connexion"));
  gtk_widget_show (label37);
  gtk_box_pack_start (GTK_BOX (hbox15), label37, FALSE, FALSE, 0);

  button_cherch_supp = gtk_button_new ();
  gtk_widget_show (button_cherch_supp);
  gtk_fixed_put (GTK_FIXED (fixed4), button_cherch_supp, 456, 120);
  gtk_widget_set_size_request (button_cherch_supp, 74, 29);

  image15 = gtk_image_new_from_stock ("gtk-clear", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image15);
  gtk_container_add (GTK_CONTAINER (button_cherch_supp), image15);

  button_prece_supp = gtk_button_new ();
  gtk_widget_show (button_prece_supp);
  gtk_fixed_put (GTK_FIXED (fixed4), button_prece_supp, 80, 504);
  gtk_widget_set_size_request (button_prece_supp, 144, 53);

  alignment14 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment14);
  gtk_container_add (GTK_CONTAINER (button_prece_supp), alignment14);

  hbox14 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox14);
  gtk_container_add (GTK_CONTAINER (alignment14), hbox14);

  image16 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image16);
  gtk_box_pack_start (GTK_BOX (hbox14), image16, FALSE, FALSE, 0);

  label36 = gtk_label_new_with_mnemonic (_("Page pr\303\251c\303\250dente"));
  gtk_widget_show (label36);
  gtk_box_pack_start (GTK_BOX (hbox14), label36, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) button_supp_dec, "clicked",
                    G_CALLBACK (on_button_supp_dec_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_cherch_supp, "clicked",
                    G_CALLBACK (on_button_cherch_supp_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_prece_supp, "clicked",
                    G_CALLBACK (on_button_prece_supp_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (SupprimerObservateur, SupprimerObservateur, "SupprimerObservateur");
  GLADE_HOOKUP_OBJECT (SupprimerObservateur, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (SupprimerObservateur, entrycherchsupp, "entrycherchsupp");
  GLADE_HOOKUP_OBJECT (SupprimerObservateur, label34, "label34");
  GLADE_HOOKUP_OBJECT (SupprimerObservateur, label35, "label35");
  GLADE_HOOKUP_OBJECT (SupprimerObservateur, button_supp_dec, "button_supp_dec");
  GLADE_HOOKUP_OBJECT (SupprimerObservateur, alignment15, "alignment15");
  GLADE_HOOKUP_OBJECT (SupprimerObservateur, hbox15, "hbox15");
  GLADE_HOOKUP_OBJECT (SupprimerObservateur, image17, "image17");
  GLADE_HOOKUP_OBJECT (SupprimerObservateur, label37, "label37");
  GLADE_HOOKUP_OBJECT (SupprimerObservateur, button_cherch_supp, "button_cherch_supp");
  GLADE_HOOKUP_OBJECT (SupprimerObservateur, image15, "image15");
  GLADE_HOOKUP_OBJECT (SupprimerObservateur, button_prece_supp, "button_prece_supp");
  GLADE_HOOKUP_OBJECT (SupprimerObservateur, alignment14, "alignment14");
  GLADE_HOOKUP_OBJECT (SupprimerObservateur, hbox14, "hbox14");
  GLADE_HOOKUP_OBJECT (SupprimerObservateur, image16, "image16");
  GLADE_HOOKUP_OBJECT (SupprimerObservateur, label36, "label36");

  return SupprimerObservateur;
}

