/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_af (void)
{
  GtkWidget *af;
  GtkWidget *fixed3;
  GtkWidget *entry1;
  GtkWidget *entry2;
  GtkWidget *entry3;
  GtkWidget *scrolledwindow1;
  GtkWidget *alignment4;
  GtkWidget *treeview;
  GtkWidget *label10;
  GtkWidget *button8;
  GtkWidget *button15;
  GtkWidget *label54;
  GtkWidget *button_af;
  GtkWidget *alignment5;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label11;
  GtkWidget *button6;
  GtkWidget *alignment17;
  GtkWidget *hbox12;
  GtkWidget *image19;
  GtkWidget *label53;
  GtkWidget *button5;
  GtkWidget *alignment16;
  GtkWidget *hbox11;
  GtkWidget *image18;
  GtkWidget *label52;
  GtkWidget *button7;
  GtkWidget *image7;
  GtkWidget *label55;
  GtkWidget *label56;

  af = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (af, 824, 600);
  gtk_window_set_title (GTK_WINDOW (af), _("Afficher"));
  gtk_window_set_position (GTK_WINDOW (af), GTK_WIN_POS_CENTER);
  gtk_window_set_resizable (GTK_WINDOW (af), FALSE);

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (af), fixed3);

  entry1 = gtk_entry_new ();
  gtk_widget_show (entry1);
  gtk_fixed_put (GTK_FIXED (fixed3), entry1, 136, 472);
  gtk_widget_set_size_request (entry1, 112, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry1), 8226);

  entry2 = gtk_entry_new ();
  gtk_widget_show (entry2);
  gtk_fixed_put (GTK_FIXED (fixed3), entry2, 136, 520);
  gtk_widget_set_size_request (entry2, 112, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry2), 8226);

  entry3 = gtk_entry_new ();
  gtk_widget_show (entry3);
  gtk_fixed_put (GTK_FIXED (fixed3), entry3, 136, 560);
  gtk_widget_set_size_request (entry3, 112, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry3), 8226);

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow1);
  gtk_fixed_put (GTK_FIXED (fixed3), scrolledwindow1, 40, 176);
  gtk_widget_set_size_request (scrolledwindow1, 736, 280);

  alignment4 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1), alignment4);

  treeview = gtk_tree_view_new ();
  gtk_widget_show (treeview);
  gtk_container_add (GTK_CONTAINER (alignment4), treeview);
  gtk_tree_view_set_rules_hint (GTK_TREE_VIEW (treeview), TRUE);
  gtk_tree_view_set_reorderable (GTK_TREE_VIEW (treeview), TRUE);

  label10 = gtk_label_new (_("Liste des observateurs"));
  gtk_widget_show (label10);
  gtk_fixed_put (GTK_FIXED (fixed3), label10, 280, 0);
  gtk_widget_set_size_request (label10, 280, 56);

  button8 = gtk_button_new_with_mnemonic (_(" Observateurs\npar nationalit\303\251"));
  gtk_widget_show (button8);
  gtk_fixed_put (GTK_FIXED (fixed3), button8, 480, 520);
  gtk_widget_set_size_request (button8, 128, 48);

  button15 = gtk_button_new_with_mnemonic (_(" Nombre total \nd'observateurs"));
  gtk_widget_show (button15);
  gtk_fixed_put (GTK_FIXED (fixed3), button15, 624, 520);
  gtk_widget_set_size_request (button15, 128, 48);

  label54 = gtk_label_new (_("ID"));
  gtk_widget_show (label54);
  gtk_fixed_put (GTK_FIXED (fixed3), label54, 88, 480);
  gtk_widget_set_size_request (label54, 49, 17);

  button_af = gtk_button_new ();
  gtk_widget_show (button_af);
  gtk_fixed_put (GTK_FIXED (fixed3), button_af, 56, 56);
  gtk_widget_set_size_request (button_af, 112, 48);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (button_af), alignment5);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label11 = gtk_label_new_with_mnemonic (_("Actualiser"));
  gtk_widget_show (label11);
  gtk_box_pack_start (GTK_BOX (hbox3), label11, FALSE, FALSE, 0);

  button6 = gtk_button_new ();
  gtk_widget_show (button6);
  gtk_fixed_put (GTK_FIXED (fixed3), button6, 632, 48);
  gtk_widget_set_size_request (button6, 128, 48);

  alignment17 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment17);
  gtk_container_add (GTK_CONTAINER (button6), alignment17);

  hbox12 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox12);
  gtk_container_add (GTK_CONTAINER (alignment17), hbox12);

  image19 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image19);
  gtk_box_pack_start (GTK_BOX (hbox12), image19, FALSE, FALSE, 0);

  label53 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label53);
  gtk_box_pack_start (GTK_BOX (hbox12), label53, FALSE, FALSE, 0);

  button5 = gtk_button_new ();
  gtk_widget_show (button5);
  gtk_fixed_put (GTK_FIXED (fixed3), button5, 328, 56);
  gtk_widget_set_size_request (button5, 128, 48);

  alignment16 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment16);
  gtk_container_add (GTK_CONTAINER (button5), alignment16);

  hbox11 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox11);
  gtk_container_add (GTK_CONTAINER (alignment16), hbox11);

  image18 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image18);
  gtk_box_pack_start (GTK_BOX (hbox11), image18, FALSE, FALSE, 0);

  label52 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label52);
  gtk_box_pack_start (GTK_BOX (hbox11), label52, FALSE, FALSE, 0);

  button7 = gtk_button_new ();
  gtk_widget_show (button7);
  gtk_fixed_put (GTK_FIXED (fixed3), button7, 296, 520);
  gtk_widget_set_size_request (button7, 48, 24);

  image7 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_container_add (GTK_CONTAINER (button7), image7);

  label55 = gtk_label_new (_("Nationalit\303\251"));
  gtk_widget_show (label55);
  gtk_fixed_put (GTK_FIXED (fixed3), label55, 24, 528);
  gtk_widget_set_size_request (label55, 96, 16);

  label56 = gtk_label_new (_("Genre"));
  gtk_widget_show (label56);
  gtk_fixed_put (GTK_FIXED (fixed3), label56, 64, 568);
  gtk_widget_set_size_request (label56, 49, 17);

  g_signal_connect ((gpointer) treeview, "row_activated",
                    G_CALLBACK (on_treeview_row_activated),
                    NULL);
  g_signal_connect ((gpointer) button8, "clicked",
                    G_CALLBACK (on_button8_clicked),
                    NULL);
  g_signal_connect ((gpointer) button15, "clicked",
                    G_CALLBACK (on_button15_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_af, "clicked",
                    G_CALLBACK (on_button_af_clicked),
                    NULL);
  g_signal_connect ((gpointer) button6, "clicked",
                    G_CALLBACK (on_button6_clicked),
                    NULL);
  g_signal_connect ((gpointer) button5, "clicked",
                    G_CALLBACK (on_button5_clicked),
                    NULL);
  g_signal_connect ((gpointer) button7, "clicked",
                    G_CALLBACK (on_button7_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (af, af, "af");
  GLADE_HOOKUP_OBJECT (af, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (af, entry1, "entry1");
  GLADE_HOOKUP_OBJECT (af, entry2, "entry2");
  GLADE_HOOKUP_OBJECT (af, entry3, "entry3");
  GLADE_HOOKUP_OBJECT (af, scrolledwindow1, "scrolledwindow1");
  GLADE_HOOKUP_OBJECT (af, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (af, treeview, "treeview");
  GLADE_HOOKUP_OBJECT (af, label10, "label10");
  GLADE_HOOKUP_OBJECT (af, button8, "button8");
  GLADE_HOOKUP_OBJECT (af, button15, "button15");
  GLADE_HOOKUP_OBJECT (af, label54, "label54");
  GLADE_HOOKUP_OBJECT (af, button_af, "button_af");
  GLADE_HOOKUP_OBJECT (af, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (af, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (af, image3, "image3");
  GLADE_HOOKUP_OBJECT (af, label11, "label11");
  GLADE_HOOKUP_OBJECT (af, button6, "button6");
  GLADE_HOOKUP_OBJECT (af, alignment17, "alignment17");
  GLADE_HOOKUP_OBJECT (af, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (af, image19, "image19");
  GLADE_HOOKUP_OBJECT (af, label53, "label53");
  GLADE_HOOKUP_OBJECT (af, button5, "button5");
  GLADE_HOOKUP_OBJECT (af, alignment16, "alignment16");
  GLADE_HOOKUP_OBJECT (af, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (af, image18, "image18");
  GLADE_HOOKUP_OBJECT (af, label52, "label52");
  GLADE_HOOKUP_OBJECT (af, button7, "button7");
  GLADE_HOOKUP_OBJECT (af, image7, "image7");
  GLADE_HOOKUP_OBJECT (af, label55, "label55");
  GLADE_HOOKUP_OBJECT (af, label56, "label56");

  return af;
}

GtkWidget*
create_aj (void)
{
  GtkWidget *aj;
  GtkWidget *fixed4;
  GtkWidget *aj2;
  GtkObject *aj1_adj;
  GtkWidget *aj1;
  GtkWidget *aj3;
  GtkWidget *aj4;
  GtkWidget *label13;
  GtkWidget *label57;
  GtkWidget *ajc;
  GtkWidget *aeg;
  GtkWidget *label58;
  GtkWidget *label59;
  GtkWidget *aj5;
  GSList *aj5_group = NULL;
  GtkWidget *label14;
  GtkWidget *button_aj;
  GtkWidget *alignment6;
  GtkWidget *hbox4;
  GtkWidget *image4;
  GtkWidget *label12;
  GtkWidget *label16;
  GtkWidget *aj6;
  GtkWidget *vsf;
  GList *vsf_items = NULL;
  GtkWidget *aj7;
  GtkWidget *aj8;
  GtkWidget *button_aff_aj_ah;

  aj = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (aj, 784, 750);
  gtk_window_set_title (GTK_WINDOW (aj), _("Ajouter"));
  gtk_window_set_position (GTK_WINDOW (aj), GTK_WIN_POS_CENTER);
  gtk_window_set_resizable (GTK_WINDOW (aj), FALSE);

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (aj), fixed4);

  aj2 = gtk_entry_new ();
  gtk_widget_show (aj2);
  gtk_fixed_put (GTK_FIXED (fixed4), aj2, 224, 120);
  gtk_widget_set_size_request (aj2, 144, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (aj2), 8226);

  aj1_adj = gtk_adjustment_new (1, 1, 100, 1, 10, 10);
  aj1 = gtk_spin_button_new (GTK_ADJUSTMENT (aj1_adj), 1, 0);
  gtk_widget_show (aj1);
  gtk_fixed_put (GTK_FIXED (fixed4), aj1, 224, 56);
  gtk_widget_set_size_request (aj1, 60, 27);

  aj3 = gtk_entry_new ();
  gtk_widget_show (aj3);
  gtk_fixed_put (GTK_FIXED (fixed4), aj3, 224, 192);
  gtk_widget_set_size_request (aj3, 144, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (aj3), 8226);

  aj4 = gtk_entry_new ();
  gtk_widget_show (aj4);
  gtk_fixed_put (GTK_FIXED (fixed4), aj4, 224, 264);
  gtk_widget_set_size_request (aj4, 144, 32);
  gtk_entry_set_text (GTK_ENTRY (aj4), _("Tunisienne"));
  gtk_entry_set_invisible_char (GTK_ENTRY (aj4), 8226);

  label13 = gtk_label_new (_("ID :"));
  gtk_widget_show (label13);
  gtk_fixed_put (GTK_FIXED (fixed4), label13, 112, 64);
  gtk_widget_set_size_request (label13, 64, 16);

  label57 = gtk_label_new (_("Date :"));
  gtk_widget_show (label57);
  gtk_fixed_put (GTK_FIXED (fixed4), label57, 120, 392);
  gtk_widget_set_size_request (label57, 64, 16);

  ajc = gtk_calendar_new ();
  gtk_widget_show (ajc);
  gtk_fixed_put (GTK_FIXED (fixed4), ajc, 224, 392);
  gtk_widget_set_size_request (ajc, 168, 184);
  gtk_calendar_display_options (GTK_CALENDAR (ajc),
                                GTK_CALENDAR_SHOW_HEADING
                                | GTK_CALENDAR_SHOW_DAY_NAMES);

  aeg = gtk_label_new (_("Sexe :"));
  gtk_widget_show (aeg);
  gtk_fixed_put (GTK_FIXED (fixed4), aeg, 80, 328);
  gtk_widget_set_size_request (aeg, 144, 24);

  label58 = gtk_label_new (_("Pr\303\251nom :"));
  gtk_widget_show (label58);
  gtk_fixed_put (GTK_FIXED (fixed4), label58, 48, 192);
  gtk_widget_set_size_request (label58, 152, 32);

  label59 = gtk_label_new (_("Nationalit\303\251 :"));
  gtk_widget_show (label59);
  gtk_fixed_put (GTK_FIXED (fixed4), label59, 40, 264);
  gtk_widget_set_size_request (label59, 152, 32);

  aj5 = gtk_radio_button_new_with_mnemonic (NULL, _("Homme"));
  gtk_widget_show (aj5);
  gtk_fixed_put (GTK_FIXED (fixed4), aj5, 240, 328);
  gtk_widget_set_size_request (aj5, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (aj5), aj5_group);
  aj5_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (aj5));

  label14 = gtk_label_new (_("Appartenance :"));
  gtk_widget_show (label14);
  gtk_fixed_put (GTK_FIXED (fixed4), label14, 72, 608);
  gtk_widget_set_size_request (label14, 112, 32);

  button_aj = gtk_button_new ();
  gtk_widget_show (button_aj);
  gtk_fixed_put (GTK_FIXED (fixed4), button_aj, 488, 672);
  gtk_widget_set_size_request (button_aj, 120, 48);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (button_aj), alignment6);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox4);

  image4 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox4), image4, FALSE, FALSE, 0);

  label12 = gtk_label_new_with_mnemonic (_("Valider"));
  gtk_widget_show (label12);
  gtk_box_pack_start (GTK_BOX (hbox4), label12, FALSE, FALSE, 0);

  label16 = gtk_label_new (_("Nom :"));
  gtk_widget_show (label16);
  gtk_fixed_put (GTK_FIXED (fixed4), label16, 56, 120);
  gtk_widget_set_size_request (label16, 152, 32);

  aj6 = gtk_radio_button_new_with_mnemonic (NULL, _("Femme"));
  gtk_widget_show (aj6);
  gtk_fixed_put (GTK_FIXED (fixed4), aj6, 392, 328);
  gtk_widget_set_size_request (aj6, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (aj6), aj5_group);
  aj5_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (aj6));

  vsf = gtk_combo_new ();
  g_object_set_data (G_OBJECT (GTK_COMBO (vsf)->popwin),
                     "GladeParentKey", vsf);
  gtk_widget_show (vsf);
  gtk_fixed_put (GTK_FIXED (fixed4), vsf, 224, 616);
  gtk_widget_set_size_request (vsf, 187, 27);
  gtk_combo_set_use_arrows_always (GTK_COMBO (vsf), TRUE);
  vsf_items = g_list_append (vsf_items, (gpointer) _("Partipolitique"));
  vsf_items = g_list_append (vsf_items, (gpointer) _("Presse"));
  vsf_items = g_list_append (vsf_items, (gpointer) _("Hote"));
  vsf_items = g_list_append (vsf_items, (gpointer) _("Societecivile"));
  vsf_items = g_list_append (vsf_items, (gpointer) _("Organisationmondiale"));
  gtk_combo_set_popdown_strings (GTK_COMBO (vsf), vsf_items);
  g_list_free (vsf_items);

  aj7 = GTK_COMBO (vsf)->entry;
  gtk_widget_show (aj7);
  gtk_entry_set_invisible_char (GTK_ENTRY (aj7), 8226);

  aj8 = gtk_check_button_new_with_mnemonic (_("Je confirme les donn\303\251es saisies"));
  gtk_widget_show (aj8);
  gtk_fixed_put (GTK_FIXED (fixed4), aj8, 184, 688);
  gtk_widget_set_size_request (aj8, 248, 24);

  button_aff_aj_ah = gtk_button_new_with_mnemonic (_("Afficher"));
  gtk_widget_show (button_aff_aj_ah);
  gtk_fixed_put (GTK_FIXED (fixed4), button_aff_aj_ah, 680, 672);
  gtk_widget_set_size_request (button_aff_aj_ah, 90, 45);

  g_signal_connect ((gpointer) button_aj, "clicked",
                    G_CALLBACK (on_button_aj_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_aff_aj_ah, "clicked",
                    G_CALLBACK (on_button_aff_aj_ah_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (aj, aj, "aj");
  GLADE_HOOKUP_OBJECT (aj, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (aj, aj2, "aj2");
  GLADE_HOOKUP_OBJECT (aj, aj1, "aj1");
  GLADE_HOOKUP_OBJECT (aj, aj3, "aj3");
  GLADE_HOOKUP_OBJECT (aj, aj4, "aj4");
  GLADE_HOOKUP_OBJECT (aj, label13, "label13");
  GLADE_HOOKUP_OBJECT (aj, label57, "label57");
  GLADE_HOOKUP_OBJECT (aj, ajc, "ajc");
  GLADE_HOOKUP_OBJECT (aj, aeg, "aeg");
  GLADE_HOOKUP_OBJECT (aj, label58, "label58");
  GLADE_HOOKUP_OBJECT (aj, label59, "label59");
  GLADE_HOOKUP_OBJECT (aj, aj5, "aj5");
  GLADE_HOOKUP_OBJECT (aj, label14, "label14");
  GLADE_HOOKUP_OBJECT (aj, button_aj, "button_aj");
  GLADE_HOOKUP_OBJECT (aj, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (aj, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (aj, image4, "image4");
  GLADE_HOOKUP_OBJECT (aj, label12, "label12");
  GLADE_HOOKUP_OBJECT (aj, label16, "label16");
  GLADE_HOOKUP_OBJECT (aj, aj6, "aj6");
  GLADE_HOOKUP_OBJECT (aj, vsf, "vsf");
  GLADE_HOOKUP_OBJECT (aj, aj7, "aj7");
  GLADE_HOOKUP_OBJECT (aj, aj8, "aj8");
  GLADE_HOOKUP_OBJECT (aj, button_aff_aj_ah, "button_aff_aj_ah");

  return aj;
}

GtkWidget*
create_mod (void)
{
  GtkWidget *mod;
  GtkWidget *fixed5;
  GtkWidget *mod2;
  GtkObject *mod1_adj;
  GtkWidget *mod1;
  GtkWidget *mod3;
  GtkWidget *mod4;
  GtkWidget *image20;
  GtkWidget *label61;
  GtkWidget *modc;
  GtkWidget *label62;
  GtkWidget *label63;
  GtkWidget *label64;
  GtkWidget *label65;
  GtkWidget *label66;
  GtkWidget *label60;
  GtkWidget *check_id;
  GtkWidget *mod5;
  GSList *mod5_group = NULL;
  GtkWidget *mod6;
  GtkWidget *mod8;
  GtkWidget *button_mod;
  GtkWidget *alignment18;
  GtkWidget *hbox13;
  GtkWidget *image21;
  GtkWidget *label67;
  GtkWidget *combo2;
  GList *combo2_items = NULL;
  GtkWidget *mod7;
  GtkWidget *button_aff_mod_ah;

  mod = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (mod, 784, 750);
  gtk_window_set_title (GTK_WINDOW (mod), _("Modifier"));
  gtk_window_set_position (GTK_WINDOW (mod), GTK_WIN_POS_CENTER);
  gtk_window_set_resizable (GTK_WINDOW (mod), FALSE);

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (mod), fixed5);

  mod2 = gtk_entry_new ();
  gtk_widget_show (mod2);
  gtk_fixed_put (GTK_FIXED (fixed5), mod2, 224, 120);
  gtk_widget_set_size_request (mod2, 144, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (mod2), 8226);

  mod1_adj = gtk_adjustment_new (1, 1, 100, 1, 10, 10);
  mod1 = gtk_spin_button_new (GTK_ADJUSTMENT (mod1_adj), 1, 0);
  gtk_widget_show (mod1);
  gtk_fixed_put (GTK_FIXED (fixed5), mod1, 360, 40);
  gtk_widget_set_size_request (mod1, 60, 27);

  mod3 = gtk_entry_new ();
  gtk_widget_show (mod3);
  gtk_fixed_put (GTK_FIXED (fixed5), mod3, 224, 192);
  gtk_widget_set_size_request (mod3, 144, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (mod3), 8226);

  mod4 = gtk_entry_new ();
  gtk_widget_show (mod4);
  gtk_fixed_put (GTK_FIXED (fixed5), mod4, 224, 264);
  gtk_widget_set_size_request (mod4, 144, 32);
  gtk_entry_set_text (GTK_ENTRY (mod4), _("Tunisienne"));
  gtk_entry_set_invisible_char (GTK_ENTRY (mod4), 8226);

  image20 = create_pixmap (mod, "index.png");
  gtk_widget_show (image20);
  gtk_fixed_put (GTK_FIXED (fixed5), image20, 512, 112);
  gtk_widget_set_size_request (image20, 192, 128);

  label61 = gtk_label_new (_("Date :"));
  gtk_widget_show (label61);
  gtk_fixed_put (GTK_FIXED (fixed5), label61, 120, 392);
  gtk_widget_set_size_request (label61, 64, 16);

  modc = gtk_calendar_new ();
  gtk_widget_show (modc);
  gtk_fixed_put (GTK_FIXED (fixed5), modc, 224, 392);
  gtk_widget_set_size_request (modc, 168, 184);
  gtk_calendar_display_options (GTK_CALENDAR (modc),
                                GTK_CALENDAR_SHOW_HEADING
                                | GTK_CALENDAR_SHOW_DAY_NAMES);

  label62 = gtk_label_new (_("Sexe :"));
  gtk_widget_show (label62);
  gtk_fixed_put (GTK_FIXED (fixed5), label62, 80, 328);
  gtk_widget_set_size_request (label62, 144, 24);

  label63 = gtk_label_new (_("Nom :"));
  gtk_widget_show (label63);
  gtk_fixed_put (GTK_FIXED (fixed5), label63, 56, 120);
  gtk_widget_set_size_request (label63, 152, 32);

  label64 = gtk_label_new (_("Pr\303\251nom :"));
  gtk_widget_show (label64);
  gtk_fixed_put (GTK_FIXED (fixed5), label64, 48, 192);
  gtk_widget_set_size_request (label64, 152, 32);

  label65 = gtk_label_new (_("Nationalit\303\251 :"));
  gtk_widget_show (label65);
  gtk_fixed_put (GTK_FIXED (fixed5), label65, 40, 264);
  gtk_widget_set_size_request (label65, 152, 32);

  label66 = gtk_label_new (_("Appartenance :"));
  gtk_widget_show (label66);
  gtk_fixed_put (GTK_FIXED (fixed5), label66, 72, 608);
  gtk_widget_set_size_request (label66, 112, 32);

  label60 = gtk_label_new (_("ID :"));
  gtk_widget_show (label60);
  gtk_fixed_put (GTK_FIXED (fixed5), label60, 256, 48);
  gtk_widget_set_size_request (label60, 64, 16);

  check_id = gtk_button_new_with_mnemonic (_("V\303\251rifier"));
  gtk_widget_show (check_id);
  gtk_fixed_put (GTK_FIXED (fixed5), check_id, 480, 40);
  gtk_widget_set_size_request (check_id, 74, 29);

  mod5 = gtk_radio_button_new_with_mnemonic (NULL, _("Homme"));
  gtk_widget_show (mod5);
  gtk_fixed_put (GTK_FIXED (fixed5), mod5, 224, 328);
  gtk_widget_set_size_request (mod5, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (mod5), mod5_group);
  mod5_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (mod5));

  mod6 = gtk_radio_button_new_with_mnemonic (NULL, _("Femme"));
  gtk_widget_show (mod6);
  gtk_fixed_put (GTK_FIXED (fixed5), mod6, 392, 328);
  gtk_widget_set_size_request (mod6, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (mod6), mod5_group);
  mod5_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (mod6));

  mod8 = gtk_check_button_new_with_mnemonic (_("Je confirme les donn\303\251es saisies"));
  gtk_widget_show (mod8);
  gtk_fixed_put (GTK_FIXED (fixed5), mod8, 184, 688);
  gtk_widget_set_size_request (mod8, 248, 24);

  button_mod = gtk_button_new ();
  gtk_widget_show (button_mod);
  gtk_fixed_put (GTK_FIXED (fixed5), button_mod, 488, 672);
  gtk_widget_set_size_request (button_mod, 120, 48);

  alignment18 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment18);
  gtk_container_add (GTK_CONTAINER (button_mod), alignment18);

  hbox13 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox13);
  gtk_container_add (GTK_CONTAINER (alignment18), hbox13);

  image21 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image21);
  gtk_box_pack_start (GTK_BOX (hbox13), image21, FALSE, FALSE, 0);

  label67 = gtk_label_new_with_mnemonic (_("Valider"));
  gtk_widget_show (label67);
  gtk_box_pack_start (GTK_BOX (hbox13), label67, FALSE, FALSE, 0);

  combo2 = gtk_combo_new ();
  g_object_set_data (G_OBJECT (GTK_COMBO (combo2)->popwin),
                     "GladeParentKey", combo2);
  gtk_widget_show (combo2);
  gtk_fixed_put (GTK_FIXED (fixed5), combo2, 224, 616);
  gtk_widget_set_size_request (combo2, 187, 27);
  gtk_combo_set_use_arrows_always (GTK_COMBO (combo2), TRUE);
  combo2_items = g_list_append (combo2_items, (gpointer) _("Partipolitique"));
  combo2_items = g_list_append (combo2_items, (gpointer) _("Presse"));
  combo2_items = g_list_append (combo2_items, (gpointer) _("Hote"));
  combo2_items = g_list_append (combo2_items, (gpointer) _("Societecivile"));
  combo2_items = g_list_append (combo2_items, (gpointer) _("Organisationmondiale"));
  gtk_combo_set_popdown_strings (GTK_COMBO (combo2), combo2_items);
  g_list_free (combo2_items);

  mod7 = GTK_COMBO (combo2)->entry;
  gtk_widget_show (mod7);
  gtk_entry_set_invisible_char (GTK_ENTRY (mod7), 8226);

  button_aff_mod_ah = gtk_button_new_with_mnemonic (_("Afficher"));
  gtk_widget_show (button_aff_mod_ah);
  gtk_fixed_put (GTK_FIXED (fixed5), button_aff_mod_ah, 664, 672);
  gtk_widget_set_size_request (button_aff_mod_ah, 82, 45);

  g_signal_connect ((gpointer) check_id, "clicked",
                    G_CALLBACK (on_check_id_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_mod, "clicked",
                    G_CALLBACK (on_button_mod_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_aff_mod_ah, "clicked",
                    G_CALLBACK (on_button_aff_mod_ah_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (mod, mod, "mod");
  GLADE_HOOKUP_OBJECT (mod, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (mod, mod2, "mod2");
  GLADE_HOOKUP_OBJECT (mod, mod1, "mod1");
  GLADE_HOOKUP_OBJECT (mod, mod3, "mod3");
  GLADE_HOOKUP_OBJECT (mod, mod4, "mod4");
  GLADE_HOOKUP_OBJECT (mod, image20, "image20");
  GLADE_HOOKUP_OBJECT (mod, label61, "label61");
  GLADE_HOOKUP_OBJECT (mod, modc, "modc");
  GLADE_HOOKUP_OBJECT (mod, label62, "label62");
  GLADE_HOOKUP_OBJECT (mod, label63, "label63");
  GLADE_HOOKUP_OBJECT (mod, label64, "label64");
  GLADE_HOOKUP_OBJECT (mod, label65, "label65");
  GLADE_HOOKUP_OBJECT (mod, label66, "label66");
  GLADE_HOOKUP_OBJECT (mod, label60, "label60");
  GLADE_HOOKUP_OBJECT (mod, check_id, "check_id");
  GLADE_HOOKUP_OBJECT (mod, mod5, "mod5");
  GLADE_HOOKUP_OBJECT (mod, mod6, "mod6");
  GLADE_HOOKUP_OBJECT (mod, mod8, "mod8");
  GLADE_HOOKUP_OBJECT (mod, button_mod, "button_mod");
  GLADE_HOOKUP_OBJECT (mod, alignment18, "alignment18");
  GLADE_HOOKUP_OBJECT (mod, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (mod, image21, "image21");
  GLADE_HOOKUP_OBJECT (mod, label67, "label67");
  GLADE_HOOKUP_OBJECT (mod, combo2, "combo2");
  GLADE_HOOKUP_OBJECT (mod, mod7, "mod7");
  GLADE_HOOKUP_OBJECT (mod, button_aff_mod_ah, "button_aff_mod_ah");

  return mod;
}

