/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>
#include <unistd.h>

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{
  GtkWidget *mod;
  GtkWidget *af;
  GtkWidget *aj;
  GtkWidget *treeview;

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  char ch[100], path[100];
  getcwd(ch, sizeof(ch));
  sprintf(path, "%s/../pixmaps",ch);
  add_pixmap_directory (path);

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */

  //mod = create_mod ();
  //gtk_widget_show (mod);
  //af = create_menu ();
  //gtk_widget_show (af);
  af = create_af ();
  gtk_widget_show (af);
  treeview=lookup_widget(af,"treeview");
  afficher(treeview,"election.txt", "", "", "");

  gtk_main ();
  return 0;
}

