/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_window2aj (void);
GtkWidget* create_window4af (void);
GtkWidget* create_window5modif (void);
GtkWidget* create_window7supp (void);
GtkWidget* create_Choix (void);
GtkWidget* create_espacevote (void);
GtkWidget* create_statistique (void);
